#!/bin/bash

mkdir -p output/myabandonware &> /dev/null
rm log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/action-2/' > output/myabandonware/action.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/adventure-3/' > output/myabandonware/adventure.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/educational-3/' > output/myabandonware/educational.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/racing-driving-4/' > output/myabandonware/racing-driving.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/role-playing-rpg-5/' > output/myabandonware/rpg.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/simulation-7/' > output/myabandonware/simulation.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/sports-8/' > output/myabandonware/sports.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/genre/strategy-6/' > output/myabandonware/strategy.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/4x-5a/' > output/myabandonware/4x.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/battlemech-6/' > output/myabandonware/battlemech.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/board-party-game-8/' > output/myabandonware/board-party-game.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/chess-d/' > output/myabandonware/chess.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/city-building-construction-simulation-3d/' > output/myabandonware/city-building-construction-simulation.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/classical-antiquity-57/' > output/myabandonware/classical-antiquity.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/cold-war-4r/' > output/myabandonware/cold-war.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/compilation-shovelware-2i/' > output/myabandonware/compilation-shovelware.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/crime-49/' > output/myabandonware/crime.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/cyberpunk-dark-sci-fi-g/' > output/myabandonware/cyberpunk-dark-sci-fi.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/d-d-ad-d-36/' > 'output/myabandonware/d&d-ad&d.csv' 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/detective-mystery-h/' > output/myabandonware/detective-mystery.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/dungeon-crawler-2l/' > output/myabandonware/dungeon-crawler.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/ecology-nature-i/' > output/myabandonware/ecology-nature.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/fps-38/' > output/myabandonware/fps.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/fantasy-16/' > output/myabandonware/fantasy.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/flight-l/' > output/myabandonware/flight.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/game-show-o/' > output/myabandonware/game-show.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/geography-p/' > output/myabandonware/geography.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/hacking-2v/' > output/myabandonware/hacking.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/helicopter-t/' > output/myabandonware/helicopter.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/historical-battle-specific-exact-u/' > output/myabandonware/historical-battle-specific-exact.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/history-v/' > output/myabandonware/history.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/horror-x/' > output/myabandonware/horror.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/interactive-fiction-10/' > output/myabandonware/interactive-fiction.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/managerial-13/' > output/myabandonware/managerial.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/math-logic-15/' > output/myabandonware/math-logic.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/medieval-4u/' > output/myabandonware/medieval.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/naval-1b/' > output/myabandonware/naval.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/norse-mythology-31/' > output/myabandonware/norse-mythology.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/post-apocalyptic-1k/' > output/myabandonware/post-apocalyptic.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/puzzle-solving-1m/' > output/myabandonware/puzzle-solving.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/rts-39/' > output/myabandonware/rts.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/real-time-1o/' > output/myabandonware/real-time.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/roguelike-3p/' > output/myabandonware/roguelike.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/science-1u/' > output/myabandonware/science.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/sci-fi-futuristic-1t/' > output/myabandonware/sci-fi-futuristic.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/shooter-1v/' > output/myabandonware/shooter.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/space-flight-47/' > output/myabandonware/space-flight.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/spy-espionage-20/' > output/myabandonware/spy-espionage.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/stealth-21/' > output/myabandonware/stealth.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/steampunk-2x/' > output/myabandonware/steampunk.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/submarine-2s/' > output/myabandonware/submarine.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/survival-horror-23/' > output/myabandonware/survival-horror.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/tank-24/' > output/myabandonware/tank.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/trade-2y/' > output/myabandonware/trade.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/train-26/' > output/myabandonware/train.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/turn-based-28/' > output/myabandonware/turn-based.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/vehicle-simulator-3y/' > output/myabandonware/vehicle-simulator.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/vehicular-combat-simulator-3z/' > output/myabandonware/vehicular-combat-simulator.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/war-4c/' > output/myabandonware/war.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/wargame-41/' > output/myabandonware/wargame.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/world-war-i-32/' > output/myabandonware/world-war-i.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/theme/world-war-ii-35/' > output/myabandonware/world-war-ii.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/amiga/' > output/myabandonware/amiga.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/amiga-cd32/' > output/myabandonware/amiga-cd32.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/cpc/' > output/myabandonware/amstrad-cpc.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/apple2/' > output/myabandonware/apple-ii.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/apple2gs/' > output/myabandonware/apple-iigs.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/atari-8-bit/' > output/myabandonware/atari-8-bit.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/atari-st/' > output/myabandonware/atari-st.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/colecovision/' > output/myabandonware/colecovision.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/commodore-16-plus4/' > output/myabandonware/commodore-16.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/c64/' > output/myabandonware/commodore-64.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/dos/' > output/myabandonware/dos.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/dragon-3264/' > output/myabandonware/dragon-32-64.csv.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/gameboy/' > output/myabandonware/game-boy.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/gameboy-color/' > output/myabandonware/game-boy-color.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/game-gear/' > output/myabandonware/game-gear.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/genesis/' > output/myabandonware/sega-genesis.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/linux/' > output/myabandonware/linux.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/mac/' > output/myabandonware/mac.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/msx/' > output/myabandonware/msx.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/nes/' > output/myabandonware/nes.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/pc88/' > output/myabandonware/pc-88.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/pc98/' > output/myabandonware/pc-98.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/sega-32x/' > output/myabandonware/sega-32x.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/sega-cd/' > output/myabandonware/sega-cd.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/sega-master-system/' > output/myabandonware/sega-master.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/snes/' > output/myabandonware/snes.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/vic-20/' > output/myabandonware/vic-20.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/windows/' > output/myabandonware/windows.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/win3x/' > output/myabandonware/windows-3.x.csv 2>> log
python3 scraper-myabandonware.py 'https://www.myabandonware.com/browse/platform/zx-spectrum/' > output/myabandonware/zx-spectrum.csv 2>> log
