#!/bin/bash

mkdir -p ratings/myabandonware &> /dev/null
rm log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/action-2/' > ratings/myabandonware/action.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/adventure-3/' > ratings/myabandonware/adventure.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/educational-3/' > ratings/myabandonware/educational.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/racing-driving-4/' > ratings/myabandonware/racing-driving.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/role-playing-rpg-5/' > ratings/myabandonware/rpg.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/simulation-7/' > ratings/myabandonware/simulation.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/sports-8/' > ratings/myabandonware/sports.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/genre/strategy-6/' > ratings/myabandonware/strategy.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/4x-5a/' > ratings/myabandonware/4x.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/battlemech-6/' > ratings/myabandonware/battlemech.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/board-party-game-8/' > ratings/myabandonware/board-party-game.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/chess-d/' > ratings/myabandonware/chess.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/city-building-construction-simulation-3d/' > ratings/myabandonware/city-building-construction-simulation.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/classical-antiquity-57/' > ratings/myabandonware/classical-antiquity.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/cold-war-4r/' > ratings/myabandonware/cold-war.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/compilation-shovelware-2i/' > ratings/myabandonware/compilation-shovelware.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/crime-49/' > ratings/myabandonware/crime.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/cyberpunk-dark-sci-fi-g/' > ratings/myabandonware/cyberpunk-dark-sci-fi.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/d-d-ad-d-36/' > 'ratings/myabandonware/d&d-ad&d.csv' 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/detective-mystery-h/' > ratings/myabandonware/detective-mystery.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/dungeon-crawler-2l/' > ratings/myabandonware/dungeon-crawler.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/ecology-nature-i/' > ratings/myabandonware/ecology-nature.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/fps-38/' > ratings/myabandonware/fps.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/fantasy-16/' > ratings/myabandonware/fantasy.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/flight-l/' > ratings/myabandonware/flight.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/game-show-o/' > ratings/myabandonware/game-show.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/geography-p/' > ratings/myabandonware/geography.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/hacking-2v/' > ratings/myabandonware/hacking.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/helicopter-t/' > ratings/myabandonware/helicopter.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/historical-battle-specific-exact-u/' > ratings/myabandonware/historical-battle-specific-exact.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/history-v/' > ratings/myabandonware/history.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/horror-x/' > ratings/myabandonware/horror.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/interactive-fiction-10/' > ratings/myabandonware/interactive-fiction.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/managerial-13/' > ratings/myabandonware/managerial.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/math-logic-15/' > ratings/myabandonware/math-logic.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/medieval-4u/' > ratings/myabandonware/medieval.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/naval-1b/' > ratings/myabandonware/naval.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/norse-mythology-31/' > ratings/myabandonware/norse-mythology.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/post-apocalyptic-1k/' > ratings/myabandonware/post-apocalyptic.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/puzzle-solving-1m/' > ratings/myabandonware/puzzle-solving.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/rts-39/' > ratings/myabandonware/rts.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/real-time-1o/' > ratings/myabandonware/real-time.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/roguelike-3p/' > ratings/myabandonware/roguelike.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/science-1u/' > ratings/myabandonware/science.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/sci-fi-futuristic-1t/' > ratings/myabandonware/sci-fi-futuristic.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/shooter-1v/' > ratings/myabandonware/shooter.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/space-flight-47/' > ratings/myabandonware/space-flight.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/spy-espionage-20/' > ratings/myabandonware/spy-espionage.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/stealth-21/' > ratings/myabandonware/stealth.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/steampunk-2x/' > ratings/myabandonware/steampunk.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/submarine-2s/' > ratings/myabandonware/submarine.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/survival-horror-23/' > ratings/myabandonware/survival-horror.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/tank-24/' > ratings/myabandonware/tank.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/trade-2y/' > ratings/myabandonware/trade.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/train-26/' > ratings/myabandonware/train.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/turn-based-28/' > ratings/myabandonware/turn-based.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/vehicle-simulator-3y/' > ratings/myabandonware/vehicle-simulator.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/vehicular-combat-simulator-3z/' > ratings/myabandonware/vehicular-combat-simulator.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/war-4c/' > ratings/myabandonware/war.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/wargame-41/' > ratings/myabandonware/wargame.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/world-war-i-32/' > ratings/myabandonware/world-war-i.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/theme/world-war-ii-35/' > ratings/myabandonware/world-war-ii.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/amiga/' > ratings/myabandonware/amiga.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/amiga-cd32/' > ratings/myabandonware/amiga-cd32.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/cpc/' > ratings/myabandonware/amstrad-cpc.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/apple2/' > ratings/myabandonware/apple-ii.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/apple2gs/' > ratings/myabandonware/apple-iigs.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/atari-8-bit/' > ratings/myabandonware/atari-8-bit.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/atari-st/' > ratings/myabandonware/atari-st.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/colecovision/' > ratings/myabandonware/colecovision.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/commodore-16-plus4/' > ratings/myabandonware/commodore-16.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/c64/' > ratings/myabandonware/commodore-64.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/dos/' > ratings/myabandonware/dos.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/dragon-3264/' > ratings/myabandonware/dragon-32-64.csv.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/gameboy/' > ratings/myabandonware/game-boy.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/gameboy-color/' > ratings/myabandonware/game-boy-color.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/game-gear/' > ratings/myabandonware/game-gear.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/genesis/' > ratings/myabandonware/sega-genesis.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/linux/' > ratings/myabandonware/linux.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/mac/' > ratings/myabandonware/mac.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/msx/' > ratings/myabandonware/msx.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/nes/' > ratings/myabandonware/nes.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/pc88/' > ratings/myabandonware/pc-88.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/pc98/' > ratings/myabandonware/pc-98.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/sega-32x/' > ratings/myabandonware/sega-32x.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/sega-cd/' > ratings/myabandonware/sega-cd.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/sega-master-system/' > ratings/myabandonware/sega-master.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/snes/' > ratings/myabandonware/snes.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/vic-20/' > ratings/myabandonware/vic-20.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/windows/' > ratings/myabandonware/windows.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/win3x/' > ratings/myabandonware/windows-3.x.csv 2>> log
python3 ratings-myabandonware.py 'https://www.myabandonware.com/browse/platform/zx-spectrum/' > ratings/myabandonware/zx-spectrum.csv 2>> log
